### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by josefnpat** [Germanunkol/GridCars#12]
I had the server running in a loop, and when it crashes, it restarts. The server basically crashed, and showed this, and then promptly restarted:

    lua: network/serverlist/advertiseOnline.lua:21: attempt to index local 'result' (a nil value)  
    stack traceback: 
    network/serverlist/advertiseOnline.lua:21: in main chunk   
     [C]: ?  

It only happened a few times, so I assume it was because someone was doing something. I have pulled to tip, and will watch to see if it happens again.

old: b0a296e
current: 42a7629

If this is just a version compatibility issue, consider making a new issue about version reporting, and closing this one.

**Comment by Germanunkol** [comment]
Hi, 
Thanks for the report!
It should have nothing to do with players - it's just the communication with the online serverlist. The http call seems to fail sometimes, which I don't catch properly - I should fix that!

However, this should not really crash the program, because I do advertisement in a seperate process (it's started via "os.execute( "lua advertiseOnline.lua" )). So only the new, seperate process crashes (i.e. one serverlist update cannot be sent for some reason or other) and the actual game is still running, though - and will try to update again in around 60 seconds.

So the question is: How do you detect a game crash? Because it seems to be failing...?

Anyway - cool system - automatically restarting the server and logging (?) the bug reports. Kudos!

**Comment by josefnpat** [comment]
I think I misinterpreted the error as a crash, since I'm used to Lua giving a stack trace, and then dying miserably. Nice job on that!

As for the restarting and logging, basically I just have a `tmux` session that I watch every so often. Not so impressive, but it gets the job done :) I've pulled to tip (42a7629..4fc9207) so we'll see if the error crops up again! Thanks!

    #!/bin/sh
    while [ true ]; do
      sleep 1;
      lua ./dedicated.lua
    done

**Comment by Germanunkol** [comment]
Ah, all right, I've only used "screen" so far.

Honestly, I don't find my method of dealing with all of this very nice - but I needed a thread-less way of doing it. I would much rather handle errors. On the "local" (non-headless) server, I use Löve's threads - which is the much cleaner solution. I can react to errors and warnings, and stop updating if, for example, the tcp port is not open. On the dedicated server, since I don't have a way to get an answer from the new process, I just have to call update again after 60 seconds, no matter how or why the last update failed.

It's a workaround, but works for now. Of course I could use some Lua thread implementation, but I have never found one that I really liked, besides the one Löve offers (which is very nice).
